version: '3.9'

services:
  postgres:
    container_name: Projeto_Ginasio
    image: postgres:15.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha123
      POSTGRES_DB: db_ginasio
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure

volumes:
  pg_data:
